### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by GrassyPlayz** [ImpactDevelopment/ImpactClient#1]
![capture](https://cloud.githubusercontent.com/assets/10326788/21077089/d86ef368-bf14-11e6-8c4e-904e8092ae57.PNG)

So uhm, what is this? Also, the website is down.

![capture](https://cloud.githubusercontent.com/assets/10326788/21077103/5f250960-bf15-11e6-8203-2e7a94cc3813.PNG)

**Comment by jonesdj1** [comment]
website prob got shutdown ^^

**Comment by jonesdj1** [comment]
Nevermind he moved it to here https://impactdevelopment.github.io/

**Comment by LeafHacker** [comment]
Thank you for taking the time to report these issues, I as @jonesdj1 said, the website has moved to https://impactdevelopment.github.io/ because of a disagreement with weebly.

I will close this since the exception can be discussed in #2, however please note this is a place to report issues for the purpose of getting them fixed in the next version. Unfortunately, we cant always provide a temporary work around.
