### ISSUE TITLE
Kill aura stopping when end crystals are between you and the opponent 

### ISSUE THREAD

**Issue by Infernopickaxe** [ImpactDevelopment/ImpactClient#1037]
Kill aura doesn't target when an end crystal is between you and the opponent

**Comment by leijurv** [comment]
you mean like... when punching would hit the end crystal not your opponent?

**Comment by Infernopickaxe** [comment]
It wont target either

**Comment by aomajn** [comment]
[This](https://youtu.be/E3OiFjCTRoI) needs to be fixed asap

**Comment by Infernopickaxe** [comment]
Aomajn's video shows the problem

**Comment by lemonsucks** [comment]
> [This](https://youtu.be/E3OiFjCTRoI) needs to be fixed asap

why is there asian asmr in ur video

**Comment by MastaNub** [comment]
im more concerned about the child breaker texture pack

**Comment by ZeroMemes** [comment]
This is because you have the "Raytrace" option on, and when it performs a raytrace to the target entity, it collides with the end crystal first and therefore determines that an attack on the target would not look legit to the server because you are hitting them through the end crystal, try turning that setting off.
