### ISSUE TITLE
Freecam conflicts with other render mods

### ISSUE THREAD

**Issue by EmeraldSnorlax** [ImpactDevelopment/ImpactClient#1107]
### What happens?
Using schematica mod. Going into freecam causes the schematica overlay to fly around with freecam
![oof](https://i.imgur.com/NNdi1rA.png)
### Exact steps to reproduce?

- Load something with Schematica
- Enter freecam

- Impact Version: Forge 1.12.2 Impact 4.6
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: Freecam, Light, ESP, StorageESP, Tracers
- Operating System: Windoze 10 64x

**Comment by ZeroMemes** [comment]
This is a schematica issue, and a legitimate one that could extend beyond Impact. I would suggest creating an issue on [their GitHub repo](https://github.com/Lunatrius/Schematica/issues) detailing that the schematic renders at the relative position to the local player, but instead of being relative to the local player it is relative to the view entity.

This issue occurs because Impact creates a separate entity that is navigated when you are in freecam, this allows things like [Baritone](https://github.com/cabaletta/baritone) to work while using it.

**Comment by leijurv** [comment]
Fixed this on schematica side and put a jar in #releases https://discordapp.com/channels/208753003996512258/378646935302701070/614274322596364298

**Comment by LeafHacker** [comment]
Upstream PR?

**Comment by leijurv** [comment]
of course
