### ISSUE TITLE
Add AirJump

### ISSUE THREAD

**Issue by VitorISs** [ImpactDevelopment/ImpactClient#111]
You should add AirJump, it's a very useful module... especially on servers that use NCP, because if you take damage, AirJump becomes a flight.

**Comment by zPeanut** [comment]
aac damage fly but with different name?

**Comment by LeafHacker** [comment]
I think even vanilla has a similar (sounding) thing. If you take damage while standing on a ghostblock\* you get launched into the air.

Cubfan showed this recently on hermitcraft, though I'm not sure who originally discovered it.

_\* A block that exists client side but not server side. Damage in the example shown was from fire _below_ the ghostblock._

**Comment by ZeroMemes** [comment]
Added in 4.2

**Comment by whz2g9** [comment]
Wen is 4.2  goun be out?

**Comment by LeafHacker** [comment]
You can ask questions on discord. This is for tracking features/bugs not
answering questions or supporting users. Your question also has nothing to
do with this specific issue.

4.2 doesn't have a release date and any estimate will probably be
inaccurate. Right now 4.2 has hardly changed since 4.1. While I'm in favour
of releasing small and often, Brady likes big exciting releases and his
release process is still rather manual for now.

On 7 Sep 2017 00:42, "whz2g9" <notifications@github.com> wrote:

Wen is 4.2 goun be out?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/ImpactDevelopment/ImpactClient/issues/111#issuecomment-327641748>,
or mute the thread
