### ISSUE TITLE
Parsed links in the MOTD dont actually work

### ISSUE THREAD

**Issue by zPeanut** [ImpactDevelopment/ImpactClient#1151]
tested on Impact 4.6 for 1.13.2, 19th April 2019

**Comment by LeafHacker** [comment]
This is caused by AWT reporting that the `Desktop` class isn't supported because `GraphicsEnvironment.isHeadless()` returns `true`.

I suspect this is because of a change in GLFW, but that is pure speculation.

Relevant code [here](https://github.com/ImpactDevelopment/Impact/blob/1c7cf9ce154b855829611d3e8a7f617a49efaa80/src/main/java/me/zero/clarinet/util/ImpactUtils.java#L169-L171) @ImpactDevelopment/impact-developer.

**Comment by LeafHacker** [comment]
This _should_ affect all Desktop stuff, including opening the file browser and web links from the Impact menu

**Comment by 0-x-2-2** [comment]
this is because of a hack for lwjgl 3 glfw to not break fully on mac if a awt class is loaded

**Comment by LeafHacker** [comment]
We can probably do the Desktop stuff in a new (headed) thread then, if minecraft has decided it wants to be headless...

**Comment by leijurv** [comment]
Fixed in 4.7
