### ISSUE TITLE
Keybind doesn't close ClickGUI when in-game

### ISSUE THREAD

**Issue by AstragoYT** [ImpactDevelopment/ImpactClient#1258]
open and close the ClickGui with the same button.
(works in Main Menu)

**Comment by LeafHacker** [comment]
This is already a thing.

**Comment by usereewrjrjeejr** [comment]
Lol

**Comment by LeafHacker** [comment]
Ok, it turns out this is broken when ingame. It works when opening clickgui from the Main Menu however.

**Comment by LeafHacker** [comment]
Interesting... If you set ClickGUI to visible (and have the hud enabled) you can see that it closes fine, but it instantly re-opens.

**Comment by Cerbiac** [comment]
To answer the question in the other post. I was using Impact 4.6 on Minecraft 1.13.2, thanks for reopening this one.

**Comment by LeafHacker** [comment]
Minecraft's keypress handler first runs key event listeners for any open GUI, and then after that it checks runs key binding listeners for the ingame stuff (but only if there's no GUI open).

What was happening was we would handle they key even once (and toggle off clickgui) but then no GUI was open so it would immediately handle the key event again (for ingame stuff) and toggle clickgui back on!

This should be fixed in the next version.

**Comment by Cerbiac** [comment]
Nice explanation.
