### ISSUE TITLE
Anti Desync causes sound of placing blocks to be silenced

### ISSUE THREAD

**Issue by a6d6061ed1** [ImpactDevelopment/ImpactClient#1287]
**Describe the bug**
Anti Desync causes sound of placing blocks to be silenced. It persist even after restarting minecraft.

**To Reproduce**
1. Enable anti desync
2. Place blocks
3. in case you can't reproduce, enable other mods that I have on as shown in the video

**Expected behavior**
Sound should be there when you place blocks

**Video**
[https://streamable.com/wfxg4](https://streamable.com/wfxg4)

**Setup**
- Impact Version: 4.6 for 1.12.2
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: as seen in the video
- Operating System: Win 10 Pro x64 1903

**Comment by leijurv** [comment]
This is fundamental to the operation of anti desync -- instead of placing the block as normal, it just tells the server and waits for confirmation before actually placing it. It wouldn't make sense to play the sound on right click, because the whole point is that the block dosen't immediately appear on right click. And since we wait for the server to respond that the block was really placed, we can't play it then, since there's no obvious way to tell if it was a block placed by you or any other reason for a block to change in the world.

**Comment by a6d6061ed1** [comment]
> This is fundamental to the operation of anti desync -- instead of placing the block as normal, it just tells the server and waits for confirmation before actually placing it. It wouldn't make sense to play the sound on right click, because the whole point is that the block dosen't immediately appear on right click. And since we wait for the server to respond that the block was really placed, we can't play it then, since there's no obvious way to tell if it was a block placed by you or any other reason for a block to change in the world.

Thank you for explaining. Features aren't described anywhere in detail so I wasn't entirely sure how it works until you told me.

**Comment by Cerbiac** [comment]
> Thank you for explaining. Features aren't described anywhere in detail so I wasn't entirely sure how it works until you told me.

I plan on working on the wiki in the future, but no time frame.
