### ISSUE TITLE
Better AutoFish

### ISSUE THREAD

**Issue by SuperOP535** [ImpactDevelopment/ImpactClient#161]
Add modes, like "fishing" and "combat" in fishing it fishes stuff and waits until a fish appears etc. in combat it uses the rod to fish on the victim.

**Comment by GlitchHead** [comment]
@ZeroMemes make sure you fix the issue with it not reeling in fast enough. It can miss fish sometimes because of this.

**Comment by mrx12335** [comment]
Autofish seems to break when the tps goes below 12

**Comment by LeafHacker** [comment]
@GlitchHead @mrx12335 Unless it's been updated, AutoFish just uses a timer on a second thread so doesn't take into account server TPS, but it TPS was low you would expect AutoFish to reel in too early, not too late.

Either way, that is a separate issue to the feature requested in this issue. This issue is about adding a combat mode that targets entities with the fishing rod. I'd recommend opening a new issue for any other bugs or suggestions.

**Comment by ZeroMemes** [comment]
Added in 4.2
