### ISSUE TITLE
Hud coordinates shouldn't use scientific notation

### ISSUE THREAD

**Issue by Joeilk** [ImpactDevelopment/ImpactClient#17]
Hud coords start bugging out after 10m. Any way to fix this?

**Comment by MattSturgeon** [comment]
Are the F3 debug screen coordinates also affected by the bug?

**Comment by ZeroMemes** [comment]
Could you leave a screenshot?

**Comment by ZeroMemes** [comment]
After further thought, you might be seeing something like "1.0000000E7". This represents 1*10^7 if you weren't aware which is the equivalent of 10 million.

**Comment by LeafHacker** [comment]
Can confirm that coordinates over 10m use scientific notation.

Re-opening since it would probably look better if they were printed in ordinary decimal since the max coord is only 30m and the player is usually more interested in the smaller units or the number.

You could use a `DecimalFormat` object when you are creating the strings, for example:

```java
		double x = 30000000.123;
		Format decistr = new DecimalFormat("#");
		System.out.println("x: " + decistr.format(x));
```

**Comment by ZeroMemes** [comment]
Fixed from April 27th's commit on the private Impact repo

**Comment by LeafHacker** [comment]
Looking good in 4.0, shame about #58 though 
![coords](https://user-images.githubusercontent.com/23565638/28998572-9223ed64-7a26-11e7-8381-bc52622babfa.png)
