### ISSUE TITLE
.peek doesn't work with held shulker boxes

### ISSUE THREAD

**Issue by RonIsBest** [ImpactDevelopment/ImpactClient#193]
If I try to type .peek while holding a shulker box nothing happens

**Comment by LeafHacker** [comment]
Please file separate issues for each bug/feature request. It also helps if you search for existing issues, since the `.locate` bug is already reported (#94).

In this case, I'll make a special exception and edit your issue instead of closing it, since one of the two things already has its own issue.

**Comment by LeafHacker** [comment]
Not sure if this is a bug or feature request. I suspect .peak isn't (currently) intended to be used with held shulker boxes, instead (aimed at?) tile entities in the world. If so then this would be a feature request.

**Comment by ZeroMemes** [comment]
Able to reproduce. Caused by the GUI being opened before the chat GUI is forcefully closed. Working on a fix.

**Comment by ZeroMemes** [comment]
Fixed in 4.2
