### ISSUE TITLE
Add BedBreaker (or Fucker)

### ISSUE THREAD

**Issue by VitorISs** [ImpactDevelopment/ImpactClient#214]
BedBreaker is a module that automatically break beds around you + through walls.
Obviously useful in the minigame Bed Wars

**Comment by LeafHacker** [comment]
Would also be useful in dimensions where beds can be used as weapons. Maybe
an option to enable only if beds are explosive would be useful.

Beds are now TileEntities (since 1.12) so it will re pretty simple to
search for them. The only complication compared with aura would be ensuring
you wait long Ng enough to not get flagged as nuker or fastbreak.

On 6 Sep 2017 17:35, "VitorISs" <notifications@github.com> wrote:

BedBreaker is a module that automatically break beds around you + through
walls.
Obviously useful in the minigame Bed Wars

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ImpactDevelopment/ImpactClient/issues/214>, or mute the
thread

**Comment by VitorISs** [comment]
closed? why?

**Comment by ZeroMemes** [comment]
Added to 4.2
