### ISSUE TITLE
Startup issue

### ISSUE THREAD

**Issue by WittleRain** [ImpactDevelopment/ImpactClient#23]
![dfgbdfgbdfgnhjmgj](https://cloud.githubusercontent.com/assets/23368823/25602703/d76b3066-2eaa-11e7-90dc-5749b06cf759.PNG)
![dfsbsdfbsdfbsdbfsd](https://cloud.githubusercontent.com/assets/23368823/25602555/c65ff4a6-2ea9-11e7-9790-ae9e9a591551.PNG)

**Comment by LeafHacker** [comment]
There are a number of problems running (most) clients from the new launcher, try using the old one.

Also, if possible, it is easier to read errors when they have been copy-pasted instead of screenshot-ed, but you've done better than most by including the error at all :D

Closing on the basis that this is related to the new launcher, if I am wrong please reopen with as much detail as possible.
