### ISSUE TITLE
Block ESP / search command

### ISSUE THREAD

**Issue by ZafotheNinja** [ImpactDevelopment/ImpactClient#241]
One command I am missing from other clients is .search. You enter the block name or I'd and it will esp that block in the area. 

Similarly, if this could be extended to a full search, like auto fly till the block is found that would be awesome too.

Thanks for all of your work on this guy's! Looking pretty awesome !

**Comment by hugohindi** [comment]
Just use xray?

**Comment by ZafotheNinja** [comment]
Xray not showing anything but mobs and chests for some reason? Also, Cray doesn't target things like sugarcane, nether/end portal block, and various others that would be annoying while xraying.

**Comment by 6BytesIn** [comment]
Have you trying to add blocks to the xray you autist

**Comment by ZafotheNinja** [comment]
Don't see the option to? Instructions unclear, hand stuck in toaster?

**Comment by LeafHacker** [comment]
This is an issue tracking a feature request for Block ESP, not a support forum. This isn't the place to teach people how to use xray.

By saying "just use xray" you are missing the point and dismissing a potentially useful idea.

Also xray isn't broken, as implied in a comment above, you just have to add blocks using `.xray add`. The xray GUI is still on the todo list.

**Comment by babbaj** [comment]
reminder to use vbos so you dont get 5fps 

https://github.com/fr1kin/ForgeHax/blob/master/src/main/java/com/matt/forgehax/mods/Markers.java

**Comment by 0-x-2-2** [comment]
babbaj: use vbo's so you don't get 5fps

**Comment by babbaj** [comment]
https://github.com/fr1kin/ForgeHax/blob/master/src/main/java/com/matt/forgehax/mods/Markers.java

here's a cool implementation for reference

**Comment by gwsm1992** [comment]
Yep. Sounds good to me. Adding tracers to the block would be the only thing to add to this.

**Comment by ZeroMemes** [comment]
Added to 4.4.

Options
- Color
- Max Blocks (Max # of blocks that will be targeted so you can manage FPS)
- Refresh Rate (How often the world will be re-scanned for target blocks, likely will change in the future)
- Width (Thickness of the outline boxes)
- Smooth Lines (Whether or not to have the outline boxes rendered with line smoothing)

The command syntax follows that of Xray and Nuker.
```
.search <add|+> <block>
.search <del|delete|rem|remove|-> <block>
.search list
```

It should be *fairly* optimized, at the max value for Max Blocks (15,000) with grass being targeted, you'll see about a frame rate drop of 50%. There is room for improvement, so that may happen before release.
