### ISSUE TITLE
Heres a list of issues

### ISSUE THREAD

**Issue by TheForgottenKing** [ImpactDevelopment/ImpactClient#28]
- ClickGUI takes a while to load on first load
- Autodisconnect crashes client
- Classic GUI: Sliders do not work, Visible button missing
- Para GUI: On a low resolution (1024x600) netbook, the lower options are missing. Upscaling to 1536x900 works. (Looks like ass though)
- If the client crashes, all changed options are not saved. There should be an option to automatically save bind changes, macros etc to disk. However, not toggling of hacks, as thats a SSD fucker.

Overall not bad Brady 9/10 would deobfuscate.

**Comment by LeafHacker** [comment]
In future please open separate issues for each problem/feature-request.

Issues can only be managed as single items, so it only makes sense to track single items in each issue.

That said, most of what you have listed are known/likely-resolved issues. 4.0 is a full rewrite (based on [ClientAPI](https://github.com/ZeroMemes/ClientAPI)), so you are much better off testing that than 3.0, since 3.0 is no longer in development.
