### ISSUE TITLE
Impact's down. RIP?

### ISSUE THREAD

**Issue by ili-codes** [ImpactDevelopment/ImpactClient#29]
So. Impact got taken down yesterday. What's next for Impact? Will it become an Injection client?

**Comment by LeafHacker** [comment]
Pretty much ever since 3.0 was released the plan was to build an injection client.

4.0 is being built on top of [ClientAPI](https://github.com/ZeroMemes/ClientAPI) which has been in development for several months now.

Luckily the DMCA takedown has happened just as 4.0 and ClientAPI are being tidied up for release.
