### ISSUE TITLE
Yaw Lock / Absolute Movement

### ISSUE THREAD

**Issue by mrx12335** [ImpactDevelopment/ImpactClient#417]
Yaw makes you walk fly or drive in a boat in a straight line. This is very useful for traveling.

**Comment by LeafHacker** [comment]
We already have a way to set yaw (and pitch) using a command. I assume this
is asking for a way to lock yaw/pitch

**Comment by mrx12335** [comment]
not to look in a straight line. I mean walking straight

**Comment by mrx12335** [comment]
example: when you walk in a nether in a2 Block tunnel you can never walk perfectly straight and you run into the walls after some time which messes up your sprint

**Comment by LeafHacker** [comment]
Yeah, the intended use case for setting look yaw is the same as this.
Basically set a yaw then walk without touching the mouse. A yaw lock would
mean you could touch the mouse without the yaw changing.

One way we could approach your suggestion is an absolute movement mode for
wasd, i.e. w is north, a is west, s south, d east, instead of being
relative to the look direction.

Another possible approach is a yaw lock module, with the option to allow
client-side-only looking (mouse movements are rendered, but don't affect
actual yaw). This may be more difficult, as you would need movements to be
calculated using the locked yaw, but rendering to use the displayed yaw.

I don't see why we couldn't implement both options, though I don't know
if/when it will happen.

**Comment by LordQuadrato** [comment]
This issue doesn't have a `Enhancement` label. Please updatel

**Comment by rebane2001** [comment]
A mini Yaw-snap would also be cool  
Eg you can look around, but it snaps to every 5 degrees

**Comment by leijurv** [comment]
Given how we already have `.rotate` i think a yaw lock / yaw snap module would be useful. 

It could either be a module that when enabled rounds your yaw to the nearest 45 degrees, then disables itself. Or it could be a module that stays enabled and keeps your yaw locked to that.

**Comment by LeafHacker** [comment]
Doing it as a persistent module makes sense. If you only want snap, toggle it twice ;-)

**Comment by leijurv** [comment]
Added in 4.7
