### ISSUE TITLE
Suggestions (Block ESP and Clean Screenshots)

### ISSUE THREAD

**Issue by NCBPFluffyBear** [ImpactDevelopment/ImpactClient#422]
Hello, here are some suggestions that I believe would help players:

### Block Esp
When you are looking for ores using X-ray, you are essentially blinded as to where you are heading. 
       If you add dirt to your X-ray list, you will be unable to see the ores.

   My suggestion is to add a feature for Block Esp. Using Block Esp, the blocks added into the Block 
       Esp list will simply be highlighted in the game, overlaying everything else, instead of making 
       everything invisible except for the blocks themselves.

### Clean ScreenShots
For people that want to funny moments with friends or report someone, screenshotting is not an option. The client overlays everything, and shutting it all down is not the fastest option. 

With Clean Screenshots, players can take screenshots without the worry of others seeing their GUI.

Thank you for reading my suggestions, I hope you take them into consideration!

**Comment by SuperOP535** [comment]
just disable hud and 1.11 is no longer supported m8

**Comment by LeafHacker** [comment]
Please open separate issues for each suggestion.

When reporting suggestions, you should delete the section related to bugs
(as explained in one of the template comments).

**Comment by LeafHacker** [comment]
I'm getting pretty sick of people implying issues are pointless and suggesting work arounds. It reinforces the idea that this is a help ticket. Even worse is when the OP accepts the work around and closes a valid issue.

If you feel a work around adds to the discussion, try and phrase it so that it doesn't invalidate the issue, or imply the OP is too stupid to think of it. 

However anyone with an ounce of common sense would know they can disable hud/render mods, and the OP already talked about disabling stuff in his report. The entire point of the suggestion is to do the disabling and reenabling for you.

**Comment by NCBPFluffyBear** [comment]
I asked in discord, someone said there was no workaround.

**Comment by ZeroMemes** [comment]
I should've closed this a while ago for multiple topics being covered in one issue. Please reopen separate issues. @NCBPFluffyBear
