### ISSUE TITLE
Re-Add ".bind reset"

### ISSUE THREAD

**Issue by InstantReflex** [ImpactDevelopment/ImpactClient#483]
Please, please, please add back .bind reset. I get that there are some risks such as accidentally removing all your binds, but I have a solution to that as you can see down below. Just have a little pop up to confirm that they actually meant to do it.

![bind reset](https://user-images.githubusercontent.com/30992296/33533461-7d9e1af4-d85e-11e7-9594-15bdb68f9ab7.png)

**Comment by Thunder33345** [comment]
i recon a undo over warning prompts 
undo will restore to last time before you reset

**Comment by InstantReflex** [comment]
> i recon a undo over warning prompts undo will restore to last time before you reset

english please?

**Comment by Thunder33345** [comment]
sorry for not begin clear @InstantReflex 
use ``.bind undo`` over warning prompts, you are more likely to accidentally click confirm out of a habit 
each time you reset the bind, it will put the old binds to a undo file which will be restored when invoking undo

**Comment by InstantReflex** [comment]
> use .bind undo over warning prompts, you are more likely to accidentally click confirm out of a habit
each time you reset the bind, it will put the old binds to a undo file which will be restored when invoking undo

`.bind reset` would reset ALL binds. So if you are clicking "Yes" out of habit, I would reconsider some life choices xD

**Comment by Thunder33345** [comment]
>``.bind reset`` would reset ALL binds. So if you are clicking "Yes" out of habit, I would reconsider some life choices xD
>EDIT: But seriously, how often does someone reset ALL binds :/

people are trained to just ignore prompts
you might not reset binds frequently, but i am sure you have at least met one of these confirmation dialogue and also have been frustrated by it deeply, your habit also carries on here
and also from a UX design standpoint, it's bad when you could have add an undo button
UNLESS the thing is irrevocable you should always use an undo after action

example:
Use UNDO after delete(since it's placed in recycle bin)
Use Prompt before shred(since it's deleted forever and cant be undo)
Use Prompt before granting an application administrator(since it's hard to undo what that application did)

see this stackexchange https://ux.stackexchange.com/q/71960/109932 for more examples

**Comment by LeafHacker** [comment]
For clarity @ZeroMemes added `.bind reset` and `.bind undo` to undo the last reset, assuming no world reloads or game restarts.

![image](https://user-images.githubusercontent.com/23565638/36287392-70deed4c-12ac-11e8-8c6e-ad3c3aea658d.png)
