### ISSUE TITLE
Great Feature for Streamers/YouTubers

### ISSUE THREAD

**Issue by InstantReflex** [ImpactDevelopment/ImpactClient#502]
There could be a mod where if you activate it, a window that copies your Minecraft opens up in another window, and has all visuals in Impact on there instead of on the main game. This would be great for any YouTuber or Streamer that wants to use Impact while recording. For example, I could have my recorder recording screen 1 (main screen), with my Minecraft, and then on my second monitor I could have my tracers, esp, xray, etc. mods on.

**Comment by MastaNub** [comment]
Make keybinds for everything and just remember them all. But seriously, I think it would be a great addition.

**Comment by LeafHacker** [comment]
This would be extremely time consuming and difficult to fully implement due to how integrated most mods are into the game and the rendering system.

I know brady has experimented in the past with similar split rendering "ghost client" stuff, but to do this for the whole client would essentially require a rewrite.

Closing as Won't Fix for now.
