### ISSUE TITLE
I didn't get a jar file with my download

### ISSUE THREAD

**Issue by helpidontwantanaccount** [ImpactDevelopment/ImpactClient#521]
Upon downloading the client i tried to run it with no success. I didn't see it when creating a new profile. I looked at the folder and there wasn't a jar file. This makes no sense, so I wondered if I could somehow get it. Thank you!

**Comment by Ilomantis** [comment]
There is no jar file, it's meant to be like that.

**Comment by SuperOP535** [comment]
it downloads it by itself

**Comment by LeafHacker** [comment]
Closing because this is almost certainly user error.

1. There is no jar file
1. There isn't supposed to be a jar file
1. You must make sure your installation is exactly correct for it to show up in the launcher
1. You must also manually create a profile in the launcher, using the version you installed. _(looks like you spotted this bit)_

I suspect you have probably added an extra directory level when putting the files in the version folder. It should be exactly `~/.minecraft/versions/1.12.1-Impact_4.1/1.12.1-Impact_4.1.json`

Or if you have attempted to install Optifine with Impact, it is possible that your folder, file and json `"id"` aren't all exactly the same (they should be).
