### ISSUE TITLE
ClickGUI: Sub options not shown on multi-option cyclers

### ISSUE THREAD

**Issue by AbstractOG** [ImpactDevelopment/ImpactClient#544]
I downloaded the new impact and reconfigured all my settings but found that in the hud mod the coordinates do not show the nether coords when your in the over world and vise versa.

I use the nether for travel and rely on the coords mod to help me not over and under travel to my destination. Please fix this as soon as possible sincerely 2b2t player PurpleYouTube

**Comment by LeafHacker** [comment]
Looking at 4.2, the Nether Coords option has disappeared... @AbstractOG You should still be able to change the setting by modifying `Impact/configs/default.json` ~~or using `.mod`~~

This bug is actually that child options aren't offered when the parent is a MultiValue cycler. Fixed in 4.3.

![image](https://user-images.githubusercontent.com/23565638/39144614-2ecd3f88-4729-11e8-95a4-432c9bc67f9a.png)
