### ISSUE TITLE
.peek issue.

### ISSUE THREAD

**Issue by TheCookCola** [ImpactDevelopment/ImpactClient#584]
When I use the .peek command it doesn't work, it doesn't pop up any way to take a look inside the shulker.

I'm using Impact 4.2, I tried it on Windows 10 and MacOs High Sierra and both doesn't work, I think is something about the hacked client.

**Comment by SuperOP535** [comment]
Peek is unnecessary, leaf added a good replacement in 4.3

**Comment by LeafHacker** [comment]
Do you get any errors in chat or the game output? `.peek` only works while holding a shulker box in your main hand, otherwise you should get the error `"You must be holding a shulker box"`. When a box is in the main hand, it will open up the shulker box GUI.

I am going to close this until you can confirm your exact steps and results, preferably with screenshots.
