### ISSUE TITLE
cant send minecraft commands after typing .spam

### ISSUE THREAD

**Issue by Zenliss** [ImpactDevelopment/ImpactClient#632]
### What happens?
I cant send minecraft commands or type in chat after i type .spam
I tried .spam out and it didnt work, i typed .spam stop
Now each time i try to send a minecraft command or type in chat it says:
[Impact] Invalid number format.
[Impact] Invalid number format.
(it says that twice)
### Exact steps to reproduce?

no idea since it happened randomly and i dont know the cause

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.2 for 1.12.2
- Using Optifine? Yes
- Enabled mods: A lot so ill just paste an imgur img https://imgur.com/a/UJh2FgR
- Operating System: Windows 10 64bit

</details>

**Comment by LordQuadrato** [comment]
**You are propably still in configuration mode (after using `.spam setup`)**
Impact wants you to type a number into the chat, corresponding to the delay between each message. That's why you're getting `Invalid number format`. Cancel it by entering `:cancel` into chat.

_If you need any further help, read through [the spammer wiki page](https://github.com/ImpactDevelopment/ImpactClient/wiki/Spammer "Created by me just now") and if this still doesn't help ask us over on [discord](https://discordapp.com/invite/YFhR2Ab "Impacts Discord")._

**Comment by ShadowWalker12** [comment]
whenever i try to do a command to stop it says added :cancel or added .spam stop
