### ISSUE TITLE
Where's 1.10.2?

### ISSUE THREAD

**Issue by WattanaGaming** [ImpactDevelopment/ImpactClient#640]
just why doesnt the site have some sort of version list anyway?

**Comment by SuperOP535** [comment]
eula

**Comment by 0-x-2-2** [comment]
Any version older than 4.0 is unavailable due to a mojang eula violation therefor only 1.12 versions exist currently on the website.

**Comment by SuperOP535** [comment]
1.11.2 also exists

**Comment by WattanaGaming** [comment]
yea and wurst also have 1.10.2 and it work just fine, whats wrong with making 1.10.2 version?

**Comment by LeafHacker** [comment]
As already discussed, the existing 1.10 versions of Impact (and all pre-4.0 versions) are illegal because they contain Minecraft and OptiFine code. Due to the licences they are released under, only the owners of those codebases are legally allowed to distribute their code.

We won't be making a new 1.10 version because the current codebase is only compatible with 1.12.2. Porting to another version is a significant effort which usually breaks almost everything. Porting to 1.10 may be as much effort as starting from scratch.

Currently the only plans are another 1.12.2 release with bugfixes followed by work on porting to 1.13 (so that we have more bugs to fix).

Regarding Wurst; as I understand it, the wurst team operate in a similar way to us; they make a client for the latest version then move on when mc updates. They won't have made any 1.10 clients since 1.11 came out. Neither will we.

Also, last I checked Wurst's releases had the same legal problems as pre-4.0 Impact, so they shouldn't be publicly distributing their client.
