### ISSUE TITLE
Discord Support

### ISSUE THREAD

**Issue by Thunder33345** [ImpactDevelopment/ImpactClient#643]
Support discord status
like Playing Impact or Minecraft
and optionally,
server IP, (maybe server gamemode parsers for certain servers?)/local world+dimension
server info like player slots
status(AFK/Idle/Active)
basically just a decently advance vanilla to discord integration
and also time elapsed

possibly also impact related, like showing using impact, and modules enabled?

**Comment by LordQuadrato** [comment]
Important: make it toggleable

**Comment by Thunder33345** [comment]
i am assuming everything will have bindable hotkeys and also macro support
also superop getting mod perm makes me jelly >.<

**Comment by ZeroMemes** [comment]
Added in 4.4.

Will close this issue once 4.4 is released so that new issues can be created for tweaks to the system. For now, anything should be discussed here.

At the moment, it displays the state of the user, (**In Menu**, **Singleplayer**, **Multiplayer**) and the gui menu that they are accessing. (**On the Main Menu**, **Choosing World**, **Browsing Server List**, **etc.**) or if they are in-game: **In Game**.

Some examples are below.

![On the Main Menu](https://i.imgur.com/K8wJ7tn.png)
![Choosing World](https://i.imgur.com/8zR7l4X.png)
![Configuring Impact](https://i.imgur.com/2nW1FOj.png)

I will likely be adding icons to go along with the current menu.

**Comment by Thunder33345** [comment]
I am thinking of single player=world name+dimension
and server=name+ip+port
realm=realm name

but nothing wrong with more configurations
for example a more unnecessary overly complex and variable system:
```
%ip = server ip
%port = server port
%servernick = the nickname given to server

%username = your username
%status = your status, can be AFK, ideal, active, PVP, mining(maybe even a command to set it)
%hp/%hunger/%armor = self explanatory

%linebreak = \n
```
which user can set it to:`Playing on $ip:$port %linebreak %status`

**Comment by leijurv** [comment]
`Will close this issue once 4.4 is released` 👌
