### ISSUE TITLE
Keybinds like Minecraft controls

### ISSUE THREAD

**Issue by SuperOP535** [ImpactDevelopment/ImpactClient#645]
You _should_ be able to bind to DELETE and some other unknown keys, __ESC__ should be used as the key for setting a keybind to NONE because this is the way Minecraft controls page works. I don't know if you can bind to ESC but it should be like ESC -> NONE, DELETE -> DELETE

Label not added because I don't know if you'll like this idea

**Comment by LeafHacker** [comment]
You can add labels without approval; nothing stops them being changed later.

As mentioned on discord (and hopefully in the changelog) this has already been added in 4.3; `Del` is now an assignable key, `Esc` will cancel modifying the Keybind and Right Click will set the Keybind to `NONE`.

Unfortunately that is about as far as we can go, since some keys aren't recognised by lwjgl. Those keys will be interpreted as `NONE` when typed. This actually caused a bug in a previous version (4.0?) where typing an unrecognised key would toggle everything assigned to `NONE`!
