### ISSUE TITLE
Show other non-storage Entities/TileEntities in an ESP

### ISSUE THREAD

**Issue by 12Me21** [ImpactDevelopment/ImpactClient#667]
There are a number of entities and tile entities that may be useful to find in an ESP, but are not relevant in StorageESP. For example End Portals, End Gateways, Minecarts, Paintings, Boats...

<details><summary><strong>Original issue</strong></summary><br />

There should be an option to display minecarts, item frames, paintings, boats, etc. while using ESP.

Also, storage ESP shows chest minecarts, but not hopper minecarts. (And maybe it would make sense to also display item frames, since they can store items too)

</details>

**Comment by LeafHacker** [comment]
I've moved the item frame and hopper minecart stuff to seperate issues and edited this to focus more on showing other non-storage stuff in an ESP.

**Comment by ZeroMemes** [comment]
Now that search has been added a couple of these can now be easily picked up.

![Search](https://i.imgur.com/7kC43qz.png)

**Comment by LeafHacker** [comment]
Whether or not this issue is now redundant depends on how performance intensive `.search` is.

Scanning through a short list of loaded tile entities will always be faster than a list of all blocks within view distance, but if the difference isn't significant enough then this should be closed as **Won't Add**.

**Comment by ZeroMemes** [comment]
Search is utilizing Baritone's [WorldScanner](https://github.com/cabaletta/baritone/blob/master/src/main/java/baritone/cache/WorldScanner.java) and could probably be optimized to use a single-chunk search method which only rescans chunks when they get updated, however, WorldScanner is about as optimized as it can get, and only requires about ~10-20ms of processing time on my system. There is no noticeable performance impact due to the multi-threading utilization.

**Comment by LeafHacker** [comment]
In that case I see no reason to duplicate functionality :party:
