### ISSUE TITLE
Some movement modules should apply to the freecam avatar & serverside player

### ISSUE THREAD

**Issue by ChristoferMinestar** [ImpactDevelopment/ImpactClient#681]
So if I leave auto-walk on, the actual character will keep walking when I'm in free-cam, just teleports back once I leave free-cam.

**Comment by ChristoferMinestar** [comment]
[Bug]

**Comment by LordQuadrato** [comment]
Seems like Freecam stops all movement packets from being sent to the server, even the ones that are coming from a movement-modifying module.

**Comment by LeafHacker** [comment]
This is simply an edge-case/usage scenario we hadn't considered.

The "avatar" you see while in freecam is a fake copy of you, left in the position you were in when you entered freecam. Technically "you" are still the camera, so any movement mods will apply to you, the camera. The "hack" is that we don't tell the server about any movement while in freecam (see #672 for an example of when this goes wrong!), so you don't get kicked for flying and you end up where you started when you exit.

There are a few exceptions to this, explicitly programmed in by us; e.g. the inventory of both you and the avatar is shared and server position updates are redirected to the avatar.

We should implement a system where things like auto-walk apply to the freecam avatar, instead of you the player. This would also require us to somehow identify whether or not a movement packet should be sent to the server.

Not sure how configurable this should be; are there any scenarios where this wouldn't be the desired behaviour?

I'll update the title for clarity.

**Comment by LeafHacker** [comment]
One possibility would be instead of cancelling all client position packets, to mutate their positions to that of the player avatar.

The only potential pitfall I can see is the potential to send more packets than expected when the camera is moving (generating packets) but the position sent is stationary each time.

Alternatively it may be possible to hook into `EntityPlayerSP`s movement/packet update code and tell it to calculate the avatar instead. This would (probably) be a cleaner result with a messier implementation!

----

In terms of modules knowing which entity to manipulate/use, I propose some kinda `Impact.instance.getPlayer()` and `.getCameraEntity()` system, where `getPlayer()` returns the avatar if freecam is active, otherwise it returns `mc.player`.

---

I'm assuming baritone should be compatible with any `Entity` subclass?

**Comment by leijurv** [comment]
No Baritone actually simulates pressing WASD LOL

**Comment by leijurv** [comment]
No longer true, Baritone now overrides the movement input in EntityPlayerSP

**Comment by leijurv** [comment]
Might close in favor of #912?

**Comment by leijurv** [comment]
Resolved by #912
