### ISSUE TITLE
Walking onto water triggers fall damage

### ISSUE THREAD

**Issue by M106** [ImpactDevelopment/ImpactClient#702]
### What happens?

The player takes "stored" fall damage (often fatal) when coming into contact with water, similar to the old bug in the vanilla game when exiting a boat onto soul sand.

### Exact steps to reproduce?
- Load survival game
- Jump around, climb up blocks and jump down repeatedly
- Find water
- Find a block level with the surface of the water and stand on it
- Walk forward to the water
- Take damage, probably die, and if so have the game give you a death message related to fall damage

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  4.3
- Using Optifine?  No
- Enabled mods:  With and without mods enabled, including fall damage mods
- Operating System:  Windows 10 64bit

</details>

**Comment by LeafHacker** [comment]
I don't think there is a solution to this, but I will leave it open until @ZeroMemes takes a look.

Unfortunately some (most) servers handle the exploits behind a few modules in this way. Since AFAIK there is no known alternative method to implement these modules, we are stuck with this behaviour.

---

What does sound interesting is that you say you have reproduced this with and without any modules enabled, that may be a seperate issue; perhaps one of the modules stays on (or partially on) even when disabled.

Can you try to reproduce by launching Impact with all modules already disabled (e.g. by temporarily renaming the `.minecraft/Impact` folder)?

**Comment by Rank1FaggetSweg** [comment]
Same issue happened to me and I didn't die in my singleplayer world when I disabled all the modules. But the issue seems to act randomly. Sometimes it may persistently kill you. Sometimes it won't. It is more common on servers.

**Comment by ThatGrzegorzB** [comment]
It's prolly related to antihunger or smth like that, if you have that module enabled and turn it off then step in water you still take damage, i think there was another module that had the same issue
