### ISSUE TITLE
Impact 4.0 Minecraft 1.12 cant use any impact tools

### ISSUE THREAD

**Issue by Sindssyge** [ImpactDevelopment/ImpactClient#705]
### What happens?
When i start minecraft and go to the impact menu the buttons are greyed out.

### Exact steps to reproduce?

- downloaded impact
- put impact in folder
- start MC with impact

- Impact Version: 4.0 for 1.12
- Using Optifine? no
- Enabled mods: unable to use mods
- Operating System: Windows 7

**Comment by MightyKnight** [comment]
Please use the most recent version of Impact, currently [Impact 4.3](http://www.mediafire.com/file/9ujvsouklxoq5hj/Impact+4.3+for+Minecraft+1.12.2.zip "Download Impact 4.3")
Versions below are not supported anymore.

**Comment by LeafHacker** [comment]
This is not a support forum, it is a bug tracker for the _latest_ version of Impact.

1. Some buttons in older versions were intentionally disabled (e.g. Xray, Macros) because the GUI they were supposed to open doesn't exist (a later version removed the disabled buttons completely).
1. If you need help with something, please use the `#help` channel on [discord](https://impactdevelopment.github.io/#contact).
1. If you have found a bug, ensure it affects the latest version, check if it is already reported and (if not) report it here.
1. If you have an idea/suggestion follow the same process as for bugs.
