### ISSUE TITLE
When using an alternate (non-qwerty) keyboard layout, Mac records the QWERTY version and Linux records the non-QWERTY version

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactClient#746]
This really broke my workflow because I have Impact/config/default.json symlinked into my dropbox so any config change I make on my Ubuntu desktop is reflected on my Mac laptop and vice versa. I also use the Dvorak keyboard layout not QWERTY. For example, if I set dvorak W, qwerty COMMA to be auto walk and then transfer that config from mac to linux, I now have to press dvorak COMMA, qwerty W.

**Comment by ZeroMemes** [comment]
This might be a ``Won't Fix`` if imma be real with u

**Comment by LeafHacker** [comment]
This'll come down to either a bad design in lwjgl or us using it poorly. Most of the time for things like game controls you want to use the raw keycode, which is based on physical position rather than logical function (and/or character association). 

IIRC we are using lwjgl's key codes, which are probably logical keycodes rather than raw/physical keycodes. Unfortunately afaik the raw keycodes may be presented differently on different platforms, so that probably isn't an option.

If I'm thinking about this correctly you should have the same issue with Minecraft's vanilla keybinds?

**Comment by leijurv** [comment]
This is a real issue that I'm continually annoyed by 😡 LOL

**Comment by SuperOP535** [comment]
because mac is dumb

**Comment by ZeroMemes** [comment]
LWJGL 2 issue that also affects the game's binding system! Marking this as wontfix.
