### ISSUE TITLE
Crosshair+ renders at the top left of the screen, not the center, in 4.4

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactClient#748]
Broken since 4.3 😠

**Comment by leijurv** [comment]
Yo this only happens with optifine sorry @ZeroMemes

**Comment by ZeroMemes** [comment]
Related to #743

**Comment by ZeroMemes** [comment]
Caused by the Anti Alias shader that Optifine applies in the ``EntityRenderer#updateCameraAndRender(float, long)`` method. Crosshair+ now uses [RenderScreenEvent](https://github.com/ImpactDevelopment/ClientAPI/blob/1.12.2/src/main/java/clientapi/load/mixin/MixinEntityRenderer.java#L53) in 4.4, and both ESP and Nametags have used it for a while. I have an idea to fix this.

**Comment by leijurv** [comment]
brady did this *dab*

**Comment by leijurv** [comment]
prankt this is not really fixed there were opengl errors in chat every 10 seconds or so

**Comment by ZeroMemes** [comment]
Fixed by https://github.com/ImpactDevelopment/ClientAPI/commit/e85ca871808932ad14979e12de7ccd8681c5cfbf
