### ISSUE TITLE
Executing Baritone's "damn" command runs fine, but causes Impact to output an invalid syntax warning.

### ISSUE THREAD

**Issue by SylveonBottle** [ImpactDevelopment/ImpactClient#842]
https://github.com/cabaletta/baritone/blob/master/src/main/java/baritone/utils/ExampleBaritoneControl.java#L451

![aehgqa 1](https://user-images.githubusercontent.com/17802843/47623682-6c587280-dae2-11e8-998b-e238f80b483b.png)

Steps to reproduce:

1. Execute `.b damn`

**Comment by ZeroMemes** [comment]
LOL

**Comment by leijurv** [comment]
LOL

**Comment by SuperOP535** [comment]
BIGGEST BUG NEEDS TO BE SOLVED __NOW__

**Comment by leijurv** [comment]
This is so that you can still say `damn` in chat on baritone standalone (with no prefix). (i.e. it's intended behavior that saying damn in baritone standalone gets passed through to chat, AND baritone also responds to it with `daniel`) Therefore, this is a wontfix from the baritone side, but Impact could still detect the `damn` message and not print the invalid syntax message even though ExampleBaritoneControl returns false.

**Comment by ZeroMemes** [comment]
Go away

**Comment by leijurv** [comment]
Fixed in 4.6
