### ISSUE TITLE
Instead of scaling up the text, increase the font size pls

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactClient#859]
<img width="941" alt="screen shot 2018-11-07 at 12 36 58 pm" src="https://user-images.githubusercontent.com/3837873/48159765-f941bf80-e28a-11e8-8061-ce84059fdba5.png">

Background image and weird lines look fine, but the font is rendered at half resolution then scaled up ree

**Comment by LeafHacker** [comment]
This is due to the way Minecraft's GUI scaling works.

We render at a given font size, and then Minecraft scales everything based on your GUI scale setting and your window size.

AFAIK there isn't anything we can do other than ignore this and hope for the best.

As a work around try setting your GUI scale to something like `Normal`.
