### ISSUE TITLE
Make it clear that Impact is *NOT* for cheating

### ISSUE THREAD

**Issue by EmeraldSnorlax** [ImpactDevelopment/ImpactClient#920]
When joining a server where utility mods aren't allowed, show a disclaimer saying that Impact does not condone cheating / or just refuse to connect

### What is your suggestion?

Add a screen that warns people / refuses to connect if the server is one where cheating isn't allowed eg Hypixel
### Why is it useful?
It will stop people who cheat playing with people who are legit and ruining their fun

Example Screen:

[Server] is a server where clients like Impact aren't allowed! By continuing, you acknowledge that you are ruining other people's games and are highly likely to get banned. Connect anyway?
< Back to server list >
< Connect anyway >

**Comment by leijurv** [comment]
Wtf is a cheating client idk bro

Impcat for sure isn't one this warning would just confuse users like wtf "cheating clients aren't allowed" why scare them like that when this isn't a cheat client

**Comment by SylveonBottle** [comment]
Was going to mention something like that. I feel like having a huge warning like this would just scare users into thinking Impact was some sort of cheating or hacking client when it isn't. All that does is give false scares and make people avoid impact. 

I know your intentions are to "provide a warning", but you gotta realize that sometimes it's better to not provide any such warning like that because all it'll do is cause scares and mass hysteria. Whether or not a warning like that would be _beneficial_ for letting users know that literally everything is "use at your own risk" for hypixel, having such a warning screen like that would only result in people avoiding Impact, making them think that it's a cheating client.

Imagine if google chrome displayed a warning saying that it can (and sometimes will, depending on what you click) download viruses onto your computer. Imagine a giant warning screen like that popping up every time you tried to login to a website. Just imagine how many people would just see the giant "WARNING" and immediately avoiding chrome for the rest of their life because of that threat.

Sure, maybe clients like impact aren't allowed on hypixel. So isn't literally everything else other than optifine and simplesprint. But I highly doubt that we're going to be the one to remind users of the rules of hypixel like that. If Impact had such a warning, and labymod didn't, then people will start assumign that labymod is allowed and impact isn't.
