### ISSUE TITLE
Inventory is blank while freecaming

### ISSUE THREAD

**Issue by Discusser** [ImpactDevelopment/ImpactClient#946]
![2019-02-24_10 11 39](https://user-images.githubusercontent.com/47938380/53297002-6fa90400-381f-11e9-8b37-dd3a402d4007.png)
![2019-02-24_10 11 44](https://user-images.githubusercontent.com/47938380/53297003-72a3f480-381f-11e9-851f-d2845287cab7.png)

### What happens?

If you have items in your inventory and you go into freecam, your items will go invisible. To make them appear again, open your inventory, or if it's in your hotbar scroll/press the number of the slot the item is in.
### Exact steps to reproduce?

- Get items in your inventory and hotbar.
- Go into Freecam.
- Press 1, 2, 3, 4, 5, 6, 7, 8, 9 to see the items in your hand but not in your hotbar.
- Open your inventory to see all of your items but once you exit, they will go invisible again.

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 
- Impact Version: 4.5 for 1.12.2
- Using Optifine?  No
- Using LiteLoader?  No
- Enabled mods: Freecam. Other mods are probably useless for this but I'll post them: AntiBlind, AntiOverlay, ClickGUI, ESP, Hud, Light, Main Menu, Nametags, StorageESP, Tracers, Trajectories, NoFall, Jesus, NoSlow, Animations, AntiHazard, AutoCheat, AutoReconnect, Inventory, ItemSaver,  MiddleClickFriend, AntiHunger, Portals, AntiBot, Criticals, HitBox, Velocity
- Operating System:  Windows 10 Home 64 bit

</details>

**Comment by LeafHacker** [comment]
This bug could be interpreted in two ways; either you shouldn't see the items in your hand or you should see the items in your inventory.

IMO the hand shouldn't be visible at all in freecam, at least by default freecam should basically be spectator mode. Although from an exploit perspective I can see how it would be useful to be able to interact with stuff away from the player.

Thoughts?

_FYI it should be pretty simple to have the freecam camera share an inventory with the player, since we did that before with the old avatar system._

**Comment by LeafHacker** [comment]
For now I've gone with the simple solution of having Freecam share the player's inveotory.
