### ISSUE TITLE
1.13 update

### ISSUE THREAD

**Issue by TheCompieter** [ImpactDevelopment/ImpactClient#956]
when are you going to update to 1.13?

**Comment by 0-x-2-2** [comment]
Probably not for a while as Mixin does not work with ForgeGradle 3.0 and ModLauncher. This is also same reason for Baritone issue here cabaletta/baritone#332.

**Comment by TheCompieter** [comment]
ok ty

**Comment by LeafHacker** [comment]
Mumfrey has said he is working on modlauncher support, but I haven't seen anything on it since https://github.com/SpongePowered/Mixin/issues/271 and Mixin hasn't been publicly worked on since https://github.com/SpongePowered/Mixin/commit/2c72246fe0b67c145db5510e66c8873df18b5a9f (July)

Hopefully he still has time to work on Mixin :/

**Comment by ZeroMemes** [comment]
The Impact codebase has been fully updated to 1.13.2, and we've been keeping it in sync with the 1.12.2 branch. 4.6 will more than likely have a simultaneous 1.12.2 and 1.13.2 release, with the following update being just 1.13.2.

**Comment by usereewrjrjeejr** [comment]
So 4.6 will work with 1.12 and 1.13?

**Comment by leijurv** [comment]
correct. 

well it'll be two different jars, but 4.6 will indeed exist with the same features on 1.12 and 1.13

**Comment by usereewrjrjeejr** [comment]
Will we see more of this?

**Comment by usereewrjrjeejr** [comment]
Nvm just saw https://github.com/ImpactDevelopment/ImpactClient/issues/956#issuecomment-473148408
