### ISSUE TITLE
Module to know the exact enchantment level of items

### ISSUE THREAD

**Issue by usereewrjrjeejr** [ImpactDevelopment/ImpactClient#957]
SUGGESTION: I believe this will make many people choose impact over the future, add something that can tell u the exact health of items. like I want to know if my sword, for example, is 32k or 7k. This is only available for 2 clients and one is backdoored and other is 30$, so this would make an impact really stand out

**Comment by leijurv** [comment]
`exact health of items` do you mean durability or enchantment level you keep switching lol

**Comment by EmeraldSnorlax** [comment]
Just... Press F3 and H.
Then hover over your items....

**Comment by ZeroMemes** [comment]
Enchantment levels should still be apparent even after they surpass level 10

```
enchantment.level.1=I
enchantment.level.2=II
enchantment.level.3=III
enchantment.level.4=IV
enchantment.level.5=V
enchantment.level.6=VI
enchantment.level.7=VII
enchantment.level.8=VIII
enchantment.level.9=IX
enchantment.level.10=X
```

Do they not appear as ``enchantment.level.32767``?

**Comment by TheForgottenKing** [comment]
This is a feature in vanilla Minecraft, please elaborate

**Comment by aomajn** [comment]
> `exact health of items` do you mean durability or enchantment level you keep switching lol

I am 100% sure that he means durability. With this thing you can see the real durability of the item that you're holding. Some 2b items have 32k durability but you can also find some items with 7k durability.

**Comment by LeafHacker** [comment]
I've heard of sharpness 32k on 2b before, but not durability.

I know it is possible to /give items with out-of-range durability since this is sometimes used for custom item skins in resource packs, etc (before 1.13 anyway). Don't remember how these items behave though, particularly when wearing down the durability... I seem to recall they don't use durability at all?

**Comment by aomajn** [comment]
On 2b these items are called unbreakables. The thing is that you can actually break them, but their durability is just higher.

**Comment by LeafHacker** [comment]
I've just had a look at how minecraft handles damage and durability and I don't see how that's possible.

Items have a `damage` and `maxDamage` value, durability is calculated on the fly as `maxDamage - damage`. `damage` can be changed (either by setting it with the /give command or by using/repairing an item) however **`maxDamage` is hardcoded** and can only be changed by modding the game.

If `damage` is more than `maxDamage` then the tool will break the next time it is used, so a "32k durability" tool would actually break the next time it is used. A 32k `maxDamage` simply isn't possible.

Try this by doing `/give @s minecraft:wooden_axe 1 32000` in singleplayer and then using the tool in survival...

---

There is an unbreakable tag, that has nothing to do with damage values (`/give @s minecraft:wooden_axe 1 0 {Unbreakable:1}`)

Setting the Unbreaking enchantment really high would also be close to unbreakable (`/give @s minecraft:wooden_axe 1 0 {ench:[{id:34,lvl:32000}]}`), this might explain where the confusion is coming from.

---

Additionally since damage is stored as an `int`, there's no reason to stop at 32k, you can go all the way to 2,147,483,647. Enchantment levels however are stored as a `short` which can only go up to 32,767.

**Comment by ZeroMemes** [comment]
I presume that the damage level is actually negative and then when calculating the remaining damage you get a higher value from subtracting a negative value!

**Comment by LeafHacker** [comment]
idk, the /give command clamps negative damage to 0

**Comment by leijurv** [comment]
Closing in favor of #1011
